### PR TITLE
Qa branch

### PR DESCRIPTION
**Pull request by JadeZYX**
finish the QA skeleton, please review..
I will fix eslint erros as soon as possible.

### CODE REVIEW

**Comment by JadeZYX** [comment]
[Questions should be related to the currently selected product](https://trello.com/c/PuqFAogl/72-questions-should-be-related-to-the-currently-selected-product)

**Comment by JadeZYX** [comment]
[Answers for Q/A](https://trello.com/c/wLpiDiz4/110-answers-for-q-a)

**Review by corneliusrenken — APPROVED** [review]
Looks good!

After you added some dynamics to the QA section I'd recommend working on tests a bit so we can reach the 70%!

And also like you said, if you find time work on some of the linting stuff 😄 

Good job!

**Comment by JadeZYX** [comment]
[Questions should be related to the currently selected product](https://trello.com/c/PuqFAogl/72-questions-should-be-related-to-the-currently-selected-product)

**Comment by JadeZYX** [comment]
[Questions should be related to the currently selected product](https://trello.com/c/PuqFAogl/72-questions-should-be-related-to-the-currently-selected-product)

**Comment by JadeZYX** [comment]
[fix linting error](https://trello.com/c/SQXqb6ki/131-fix-linting-error)

**Pull request merged**
