### PR TITLE
Implementation of carousel component, Some other changes to my previous components to conform to the carousel's creation

### PR DESCRIPTION
**Pull request by Corbin**
- implemented Carousel component (does not only show supposed visible cards in the dom anymore, and shows all)
- Made some refactoring changes to product cards to conform to the carousel component implementation
- Wrote test suite for the carousel component

Still need to add the action button for the cards that will either remove the product from the outfit carousel or show a comparison modal for the related products carousel (_Probably going to do that via mapping within the carousel component_)

### CODE REVIEW

**Comment by Corbin** [comment]
[Related Products List](https://trello.com/c/nErmg0Ls/102-related-products-list)

**Review by corneliusrenken — APPROVED** [review]
Looks great! Great work with all the testing!

**Comment by corneliusrenken** [comment]
Also I feel the way you wrote out your styles will make it very easy if you ever want to switch to styled components which is nice! Although this works just as well

**Comment by Corbin** [comment]
> 

Yeah I plan on converting everything to styled components

**Pull request merged**
