### PR TITLE
Cart Section

### PR DESCRIPTION
**Pull request by corneliusrenken**
Decided to add these cards together as the CustomDropdown component was already approved and more or less just implemented into the code.

Includes:
- Size Selector - 1.1.3.1 in BRD
- Quantity Selector - 1.1.3.2 in BRD
- Add to Cart Button - 1.1.3.3 in BRD
- Helper function to convert style into an array of custom sku objects

- tests for everything above

**MISSING:** I didn't implement the add to cart API request yet as we don't have the server set up. At the moment there's just a console log with all the info we'd need.

### CODE REVIEW

**Comment by corneliusrenken** [comment]
[Cart Section: Add to Cart](https://trello.com/c/8yyabJHo/94-cart-section-add-to-cart)

**Comment by corneliusrenken** [comment]
[Cart Section: Size Selector](https://trello.com/c/EF0j1iwn/92-cart-section-size-selector)

**Comment by corneliusrenken** [comment]
[Cart Section: Quantity Selector](https://trello.com/c/bZ73JF7b/93-cart-section-quantity-selector)

**Comment by JadeZYX** [comment]
Your work looks organized, clean and neat!
Perfect!!

**Review by JadeZYX — APPROVED** [review]
Your work looks organized, clean and neat.
Perfect!!

**Pull request merged**
